# Page settings
baseurl = "/"
title = "Bepoz Support"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]

  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = ""
  description = "Support Links for Bepoz America LLC support"
  email = ""
  # Navigation
  [params.navigation]
    brand = "Bepoz"
    home = "Home"
    work = "Support Tools"
    testimonials = "Warnings"
    services = "Support Applications"
    about = "About"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10

  # Hero section
  [params.hero]
    title = "Bepoz is here to Help"
    subtitle = 'On this site you will find tools to help you with a guid of a Bepoz techintion resolve your issues quickly'

  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]
  img = "http://проф-обр.рф/_ld/1/69916522.jpg"

  [[params.intro.item]]
    title = "Bepoz Remote Support"
    description = "Allow techinon to remote support"
    url = "https://zinfandel.centrastage.net/csm/profile/downloadAgent/643bd879-3bed-47af-837a-d832cd6522a8"
    button = "Download and Run"
    icon = "CentraStageIcon.png"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Information Hub"
    description = "You can find helpful training material and basic information about the Bepoz software from the link below"
    url = "https://bepozglobal.atlassian.net/wiki/spaces/SP"
    button = "Start Learning"
    icon = "Grad_Cap.svg"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Customer Documents"
    description = "For all documents on ender user operations for Bepoz or Bepoz related software please navigate to the link provided"
    url = "https://bepozglobal.atlassian.net/wiki/spaces/KNOW/pages/84621762/Bepoz+End+User+Documents"
    button = "Get Started"
    icon = "paper.svg"
    img = "img_7.jpg"

  [params.intro.video]
    enable = false
    title = "Watch the video"
    icon = "icon-play2"
    url = "https://vimeo.com/channels/staffpicks/93951774"


  # Work section
  [params.work]
    enable = false
    title = "Support Tools"
    description = "Please choose one of the tools bellow"
    footertext = '** use the above tools at your own risk'

    [[params.work.row]]
      img = "Bepoz_CentraStage.png"
      alt = "Bepoz Remote Support"
      title = "Bepoz_CentraStage.png"
      subtitle = "Download and Run"
      link = "https://zinfandel.centrastage.net/csm/profile/downloadAgent/643bd879-3bed-47af-837a-d832cd6522a8"

    [[params.work.row]]
      img = "work_2.jpg"
      alt = "Image2"
      title = "Project 2"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_3.jpg"
      alt = "Image3"
      title = "Project 3"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_4.jpg"
      alt = "Image4"
      title = "Project 4"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_5.jpg"
      alt = "Image5"
      title = "Project 5"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_6.jpg"
      alt = "Image6"
      title = "Project 6"
      subtitle = "Design"

  # Testimonials section
  [params.testimonials]
    enable = false
    title = "Testimonials"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.&rdquo;"
      person = 'Jean Doe, CEO <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person1.jpg"
      alt = "Person1"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.&rdquo;"
      person = 'John Doe, Senior UI <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person2.jpg"
      alt = "Person2"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. &rdquo;"
      person = 'Chris Nash, Director <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person3.jpg"
      alt = "Person3"




  # Services section
  [params.services]
    enable = true
    title = "Tools"
    description = "Please only run with Bepoz Technician supervision. Bepoz cannot beheld liable for the use of these tool with out direction from Bepoz Technician. Please reachout to support for any issues."
    [[params.services.item]]
      title = "Paylink Removal"
      description = "Please only run with Bepoz Technician supervision. Removes paylink for re-install"
      icon = "icon-anchor"
      urlserv = "http://d1wzjmpxmd6fyh.cloudfront.net/software/PaylinkRemoval.bat"
      buttonserv = "Download and Run"
    [[params.services.item]]
      title = "Centra Stage Cleaner"
      description = "Please only run with Bepoz Technician supervision. Cleans Up Centra Stage for a clean install"
      icon = "icon-layers2"
      urlserv = "http://d1wzjmpxmd6fyh.cloudfront.net/software/remove_centrastage.exe"
      buttonserv = "Download and Run"
    [[params.services.item]]
      title = "Ethernet Configuration"
      description = "This tool will help with finding and setting the EPSON installs"
      icon = "icon-video2"
      urlserv = "http://d1wzjmpxmd6fyh.cloudfront.net/software/EtherConfig.exe"
      buttonserv = "Download and Run"
      [[params.services.item]]
      title = "IP Scan"
      description = "This tool will help with scanning the network for all devices"
      icon = "icon-monitor"
      urlserv = "http://d1wzjmpxmd6fyh.cloudfront.net/software/ipscan25.exe"
      buttonserv = "Download and Run"
	  [[params.services.item]]
      title = "Speed Fan"
      description = "Used to view the current PC temperature"
      icon = "icon-monitor"
      urlserv = "http://d1wzjmpxmd6fyh.cloudfront.net/software/instspeedfan452.exe"
      buttonserv = "Download and Run"
	  [[params.services.item]]
      title = "Com Test"
      description = "Used to test Com Ports to see replys form serial devices"
      icon = "icon-monitor"
      urlserv = "http://d1wzjmpxmd6fyh.cloudfront.net/software/Install_ComTestSerial_3_1_0_129.exe"
      buttonserv = "Download and Run"
  # About section
  [params.about]
    enable = false
    title = "About"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.about.item]]
      name = "Jean Smith"
      position = "Web Designer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person1.jpg"
      alt = "Person1"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-linkedin", "#"]
      ]

    [[params.about.item]]
      name = "Rob Smith"
      position = "Web Developer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person2.jpg"
      alt = "Person2"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-github", "#"]
      ]

    [[params.about.item]]
      name = "Larry Ben"
      position = "Web Designer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person3.jpg"
      alt = "Person3"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-dribbble", "#"]
      ]

  # Counters section
  [params.counters]
    enable = false
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Finished projects"
      icon = "icon-briefcase"
      from = 0
      to = 89
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Lines of code"
      icon = "icon-code"
      from = 0
      to = 2343409
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Cups of coffee"
      icon = "icon-cup"
      from = 0
      to = 1302
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Happy clients"
      icon = "icon-people"
      from = 0
      to = 52
      interval = 50
      speed = 5000
  # billing section
  [params.billing]
    enable = true
  # Contact section
  [params.contact]
    enable = true
    map = false
    title = "Get in touch"
    description = "Bepoz support is here for you. Please reach out to use using one of the methods bellow"
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "111 Clebour Street,Fort Mill SC 29715 <br> Bepoz Support"],
        ["icon-phone", "+1 (803) 802-2404 Option 2"],
        ["icon-envelope", "Support@bepoz.com"],
        ["icon-globe", '<a href="http://bepoz.com/" target="_blank">bepoz.com</a>']
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = false
    copyright = '&copy; Elate Free HTML5. All Rights Reserved. <br>Created by <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> Images: <a href="http://pexels.com/" target="_blank">Pexels</a>, <a href="http://plmd.me/" target="_blank">plmd.me</a> <br>Hugo port by: <a href="https://github.com/saey55" target="_blank">saey55</a>'
