# Page settings
baseurl = "/"
title = "Bepoz Support"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]

  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = ""
  description = "Support Links for Bepoz America LLC support"
  email = ""
  # Navigation
  [params.navigation]
    brand = "Bepoz"
    home = "Home"
    work = "Support Tools"
    testimonials = "Warnings"
    services = "Support Applications"
    about = "About"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10

  # Hero section
  [params.hero]
    title = "Bepoz is here to Help"
    subtitle = 'On this site you will find tools to help guide you and your Bepoz Technician to a quick resolution of your technical issues'

  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]
  img = "http://проф-обр.рф/_ld/1/69916522.jpg"

  [[params.intro.item]]
    title = "Bepoz Remote Support"
    description = "Allow a Technician to remote support"
    url = "https://zinfandel.centrastage.net/csm/profile/downloadAgent/643bd879-3bed-47af-837a-d832cd6522a8"
    button = "Download and Run"
    icon = "CentraStageIcon.png"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Information Hub"
    description = "You can find helpful training material and basic information about the Bepoz software from the link below"
    url = "https://bepozglobal.atlassian.net/wiki/spaces/SP"
    button = "Start Learning"
    icon = "Grad_Cap.svg"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Customer Documents"
    description = "For all documents on user operations or Bepoz related software please click the link below"
    url = "https://bepozglobal.atlassian.net/wiki/spaces/KNOW/pages/84621762/Bepoz+End+User+Documents"
    button = "Get Started"
    icon = "paper.svg"
    img = "img_7.jpg"

  [params.intro.video]
    enable = false
    title = "Watch the video"
    icon = "icon-play2"
    url = "https://vimeo.com/channels/staffpicks/93951774"


  # Work section
  [params.work]
    enable = false
    title = "Support Tools"
    description = "Please choose one of the tools bellow"
    footertext = '** use the above tools at your own risk'

    [[params.work.row]]
      img = "Bepoz_CentraStage.png"
      alt = "Bepoz Remote Support"
      title = "Bepoz_CentraStage.png"
      subtitle = "Download and Run"
      link = "https://zinfandel.centrastage.net/csm/profile/downloadAgent/643bd879-3bed-47af-837a-d832cd6522a8"

    [[params.work.row]]
      img = "work_2.jpg"
      alt = "Image2"
      title = "Project 2"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_3.jpg"
      alt = "Image3"
      title = "Project 3"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_4.jpg"
      alt = "Image4"
      title = "Project 4"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_5.jpg"
      alt = "Image5"
      title = "Project 5"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_6.jpg"
      alt = "Image6"
      title = "Project 6"
      subtitle = "Design"

  # Testimonials section
  [params.testimonials]
    enable = false
    title = "Testimonials"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.&rdquo;"
      person = 'Jean Doe, CEO <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person1.jpg"
      alt = "Person1"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.&rdquo;"
      person = 'John Doe, Senior UI <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person2.jpg"
      alt = "Person2"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. &rdquo;"
      person = 'Chris Nash, Director <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person3.jpg"
      alt = "Person3"




  # Services section
  [params.services]
    enable = true
    title = "Tools"
    description = "These tools are here to help but please only run with Bepoz Technician supervision. Bepoz cannot be held liable for the use of these tools without direction from a Bepoz Technician. Please reachout to the support team with any issues."
    [[params.services.item]]
      title = "Paylink Removal"
      description = "Must only use this tool with Bepoz Technician supervision. It is used to remove Paylink for re-install"
      icon = "icon-anchor"
      urlserv = "http://d1wzjmpxmd6fyh.cloudfront.net/software/PaylinkRemoval.bat"
      buttonserv = "Download and Run"
    [[params.services.item]]
      title = "Centra Stage Cleaner"
      description = "Must only use this tool with Bepoz Technician supervision. It is used to clean up Centra Stage for a smooth install"
      icon = "icon-layers2"
      urlserv = "http://d1wzjmpxmd6fyh.cloudfront.net/software/remove_centrastage.exe"
      buttonserv = "Download and Run"
    [[params.services.item]]
      title = "Ethernet Configuration"
      description = "This tool is used to configure your EPSON printer"
      icon = "icon-video2"
      urlserv = "http://d1wzjmpxmd6fyh.cloudfront.net/software/EtherConfig.exe"
      buttonserv = "Download and Run"
      [[params.services.item]]
      title = "IP Scan"
      description = "This tool is used to scan devices on the local network"
      icon = "icon-monitor"
      urlserv = "http://d1wzjmpxmd6fyh.cloudfront.net/software/ipscan25.exe"
      buttonserv = "Download and Run"
	  [[params.services.item]]
      title = "Speed Fan"
      description = "This tool is used to view the current PC temperature"
      icon = "icon-monitor"
      urlserv = "http://d1wzjmpxmd6fyh.cloudfront.net/software/instspeedfan452.exe"
      buttonserv = "Download and Run"
	  [[params.services.item]]
      title = "Com Test"
      description = "This tool is used to test the communication of your serial device"
      icon = "icon-monitor"
      urlserv = "http://d1wzjmpxmd6fyh.cloudfront.net/software/Install_ComTestSerial_3_1_0_129.exe"
      buttonserv = "Download and Run"
  # About section
  [params.about]
    enable = true
    title = "Support Cost"
    description = "Please read the information below regarding Billable vs Non-billable time. All phone calls are considered billable, until determined otherwise. Support emails can be sent to Support@bepoz.com regardless of billable or non billable."
    TableHeader1 = "Role"
    TableHeader2 = "Hours"
    [[params.about.InfoTabs]]
    description = "Click the tabs for more information"
    [[params.about.ExtraBillableNotes]]
      description = "Note: Break Fix Support consist of errors or software reported issues. If the system or hardware was pre-existing working then stopped working this would not be covered under non-billable."
      severity = "danger"
      alerts = "hours"
    [[params.about.ExtraBillableNotes]]
      description = "[1]:Normal business hours are 8:00pm to 6:30pm est. M-F. Excluding holidays"
      severity = "info"
    [[params.about.ExtraBillableNotes]]
      description = "[2] Adavnced research on non standard configurations is considered billable."
      severity = "info"
      alerts = "advanced"
    [[params.about.ExtraAdvancedNotes]]
      description = "[2] A new project is considered advanced research. Planning will be needed in order to duplicate these or similar features."
      severity = "info"
      alerts = "advanced"
  # Counters section
  [params.counters]
    enable = false
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Finished projects"
      icon = "icon-briefcase"
      from = 0
      to = 89
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Lines of code"
      icon = "icon-code"
      from = 0
      to = 2343409
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Cups of coffee"
      icon = "icon-cup"
      from = 0
      to = 1302
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Happy clients"
      icon = "icon-people"
      from = 0
      to = 52
      interval = 50
      speed = 5000
  # billing section
  [params.billing]
    enable = true
  # Contact section
  [params.contact]
    enable = true
    map = false
    title = "Get in touch"
    description = "Bepoz support is here for you. Please reach out to us using one of the methods below"
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "111 Clebourne Street, Fort Mill SC 29715 <br> Bepoz Support"],
        ["icon-phone", "+1 (803) 802-2404 Option 2"],
        ["icon-envelope", "Support@bepoz.com"],
        ["icon-globe", '<a href="http://bepoz.com/" target="_blank">bepoz.com</a>']
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = false
    copyright = '&copy; Elate Free HTML5. All Rights Reserved. <br>Created by <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> Images: <a href="http://pexels.com/" target="_blank">Pexels</a>, <a href="http://plmd.me/" target="_blank">plmd.me</a> <br>Hugo port by: <a href="https://github.com/saey55" target="_blank">saey55</a>'
